// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/tracer/service.proto

package tracer

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FetchTraceDataRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	FromUnixTimestamp uint64                 `protobuf:"varint,1,opt,name=from_unix_timestamp,json=fromUnixTimestamp,proto3" json:"from_unix_timestamp,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *FetchTraceDataRequest) Reset() {
	*x = FetchTraceDataRequest{}
	mi := &file_api_tracer_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchTraceDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchTraceDataRequest) ProtoMessage() {}

func (x *FetchTraceDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_tracer_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchTraceDataRequest.ProtoReflect.Descriptor instead.
func (*FetchTraceDataRequest) Descriptor() ([]byte, []int) {
	return file_api_tracer_service_proto_rawDescGZIP(), []int{0}
}

func (x *FetchTraceDataRequest) GetFromUnixTimestamp() uint64 {
	if x != nil {
		return x.FromUnixTimestamp
	}
	return 0
}

type FetchTraceDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*Node                `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Links         []*Span                `protobuf:"bytes,2,rep,name=links,proto3" json:"links,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchTraceDataResponse) Reset() {
	*x = FetchTraceDataResponse{}
	mi := &file_api_tracer_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchTraceDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchTraceDataResponse) ProtoMessage() {}

func (x *FetchTraceDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_tracer_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchTraceDataResponse.ProtoReflect.Descriptor instead.
func (*FetchTraceDataResponse) Descriptor() ([]byte, []int) {
	return file_api_tracer_service_proto_rawDescGZIP(), []int{1}
}

func (x *FetchTraceDataResponse) GetNodes() []*Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *FetchTraceDataResponse) GetLinks() []*Span {
	if x != nil {
		return x.Links
	}
	return nil
}

type Node struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_api_tracer_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_api_tracer_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_api_tracer_service_proto_rawDescGZIP(), []int{2}
}

func (x *Node) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Span struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Target        string                 `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	Data          *SpanData              `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Span) Reset() {
	*x = Span{}
	mi := &file_api_tracer_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Span) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Span) ProtoMessage() {}

func (x *Span) ProtoReflect() protoreflect.Message {
	mi := &file_api_tracer_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Span.ProtoReflect.Descriptor instead.
func (*Span) Descriptor() ([]byte, []int) {
	return file_api_tracer_service_proto_rawDescGZIP(), []int{3}
}

func (x *Span) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Span) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *Span) GetData() *SpanData {
	if x != nil {
		return x.Data
	}
	return nil
}

type SpanData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalCount    int64                  `protobuf:"varint,1,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpanData) Reset() {
	*x = SpanData{}
	mi := &file_api_tracer_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpanData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpanData) ProtoMessage() {}

func (x *SpanData) ProtoReflect() protoreflect.Message {
	mi := &file_api_tracer_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpanData.ProtoReflect.Descriptor instead.
func (*SpanData) Descriptor() ([]byte, []int) {
	return file_api_tracer_service_proto_rawDescGZIP(), []int{4}
}

func (x *SpanData) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

var File_api_tracer_service_proto protoreflect.FileDescriptor

const file_api_tracer_service_proto_rawDesc = "" +
	"\n" +
	"\x18api/tracer/service.proto\x12\x06tracer\x1a api/google/api/annotations.proto\"G\n" +
	"\x15FetchTraceDataRequest\x12.\n" +
	"\x13from_unix_timestamp\x18\x01 \x01(\x04R\x11fromUnixTimestamp\"`\n" +
	"\x16FetchTraceDataResponse\x12\"\n" +
	"\x05nodes\x18\x01 \x03(\v2\f.tracer.NodeR\x05nodes\x12\"\n" +
	"\x05links\x18\x02 \x03(\v2\f.tracer.SpanR\x05links\"\x16\n" +
	"\x04Node\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\\\n" +
	"\x04Span\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\x12$\n" +
	"\x04data\x18\x03 \x01(\v2\x10.tracer.SpanDataR\x04data\"+\n" +
	"\bSpanData\x12\x1f\n" +
	"\vtotal_count\x18\x01 \x01(\x03R\n" +
	"totalCount2\xa9\x01\n" +
	"\rTracerService\x12\x97\x01\n" +
	"\x0eFetchTraceData\x12\x1d.tracer.FetchTraceDataRequest\x1a\x1e.tracer.FetchTraceDataResponse\"F\x82\xd3\xe4\x93\x02@Z*\x12(/v1/fetchTraceData/{from_unix_timestamp}\x12\x12/v1/fetchTraceDataB,Z*github.com/ServiGraph/servilens/api/tracerb\x06proto3"

var (
	file_api_tracer_service_proto_rawDescOnce sync.Once
	file_api_tracer_service_proto_rawDescData []byte
)

func file_api_tracer_service_proto_rawDescGZIP() []byte {
	file_api_tracer_service_proto_rawDescOnce.Do(func() {
		file_api_tracer_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_tracer_service_proto_rawDesc), len(file_api_tracer_service_proto_rawDesc)))
	})
	return file_api_tracer_service_proto_rawDescData
}

var file_api_tracer_service_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_tracer_service_proto_goTypes = []any{
	(*FetchTraceDataRequest)(nil),  // 0: tracer.FetchTraceDataRequest
	(*FetchTraceDataResponse)(nil), // 1: tracer.FetchTraceDataResponse
	(*Node)(nil),                   // 2: tracer.Node
	(*Span)(nil),                   // 3: tracer.Span
	(*SpanData)(nil),               // 4: tracer.SpanData
}
var file_api_tracer_service_proto_depIdxs = []int32{
	2, // 0: tracer.FetchTraceDataResponse.nodes:type_name -> tracer.Node
	3, // 1: tracer.FetchTraceDataResponse.links:type_name -> tracer.Span
	4, // 2: tracer.Span.data:type_name -> tracer.SpanData
	0, // 3: tracer.TracerService.FetchTraceData:input_type -> tracer.FetchTraceDataRequest
	1, // 4: tracer.TracerService.FetchTraceData:output_type -> tracer.FetchTraceDataResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_tracer_service_proto_init() }
func file_api_tracer_service_proto_init() {
	if File_api_tracer_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_tracer_service_proto_rawDesc), len(file_api_tracer_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_tracer_service_proto_goTypes,
		DependencyIndexes: file_api_tracer_service_proto_depIdxs,
		MessageInfos:      file_api_tracer_service_proto_msgTypes,
	}.Build()
	File_api_tracer_service_proto = out.File
	file_api_tracer_service_proto_goTypes = nil
	file_api_tracer_service_proto_depIdxs = nil
}
