// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: api/tracer/service.proto

package tracer

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TracerService_FetchTraceData_FullMethodName = "/tracer.TracerService/FetchTraceData"
)

// TracerServiceClient is the client API for TracerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TracerServiceClient interface {
	FetchTraceData(ctx context.Context, in *FetchTraceDataRequest, opts ...grpc.CallOption) (*FetchTraceDataResponse, error)
}

type tracerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTracerServiceClient(cc grpc.ClientConnInterface) TracerServiceClient {
	return &tracerServiceClient{cc}
}

func (c *tracerServiceClient) FetchTraceData(ctx context.Context, in *FetchTraceDataRequest, opts ...grpc.CallOption) (*FetchTraceDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FetchTraceDataResponse)
	err := c.cc.Invoke(ctx, TracerService_FetchTraceData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TracerServiceServer is the server API for TracerService service.
// All implementations must embed UnimplementedTracerServiceServer
// for forward compatibility.
type TracerServiceServer interface {
	FetchTraceData(context.Context, *FetchTraceDataRequest) (*FetchTraceDataResponse, error)
	mustEmbedUnimplementedTracerServiceServer()
}

// UnimplementedTracerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTracerServiceServer struct{}

func (UnimplementedTracerServiceServer) FetchTraceData(context.Context, *FetchTraceDataRequest) (*FetchTraceDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchTraceData not implemented")
}
func (UnimplementedTracerServiceServer) mustEmbedUnimplementedTracerServiceServer() {}
func (UnimplementedTracerServiceServer) testEmbeddedByValue()                       {}

// UnsafeTracerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TracerServiceServer will
// result in compilation errors.
type UnsafeTracerServiceServer interface {
	mustEmbedUnimplementedTracerServiceServer()
}

func RegisterTracerServiceServer(s grpc.ServiceRegistrar, srv TracerServiceServer) {
	// If the following call pancis, it indicates UnimplementedTracerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TracerService_ServiceDesc, srv)
}

func _TracerService_FetchTraceData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchTraceDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TracerServiceServer).FetchTraceData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TracerService_FetchTraceData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TracerServiceServer).FetchTraceData(ctx, req.(*FetchTraceDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TracerService_ServiceDesc is the grpc.ServiceDesc for TracerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TracerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tracer.TracerService",
	HandlerType: (*TracerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FetchTraceData",
			Handler:    _TracerService_FetchTraceData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/tracer/service.proto",
}
